#ifndef ASSEMBLY_INFO_H
#define ASSEMBLY_INFO_H

#define VER_FILEVERSION             1,0,0,0
#define VER_FILEVERSION_STR         "1.0.0.0\0"

#define VER_PRODUCTVERSION          VER_FILEVERSION
#define VER_PRODUCTVERSION_STR      VER_FILEVERSION_STR

#define VER_PRODUCTNAME_STR         "Borke"
#define VER_FILEDESCRIPTION_STR     VER_PRODUCTNAME_STR
#define VER_INTERNALNAME_STR        VER_PRODUCTNAME_STR
#define VER_ORIGINALFILENAME_STR    "borke.exe"

#define VER_COMPANYNAME_STR         ""
#define VER_LEGALCOPYRIGHT_STR      "Copyright © 2017 Przemys³aw Gawlas"
#define VER_LEGALTRADEMARKS1_STR    ""
#define VER_LEGALTRADEMARKS2_STR    VER_LEGALTRADEMARKS1_STR

#define VER_COMPANYDOMAIN_STR       ""//stona

#endif // ASSEMBLY_INFO_H
